CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS collection_runs (
    run_id uuid PRIMARY KEY,
    source_fingerprint char(64) NOT NULL,
    source_path text NOT NULL,
    embedding_model text NOT NULL,
    full_snapshot boolean NOT NULL DEFAULT false,
    status text NOT NULL CHECK (status IN ('running', 'succeeded', 'failed')),
    document_count integer NOT NULL DEFAULT 0 CHECK (document_count >= 0),
    provision_count integer NOT NULL DEFAULT 0 CHECK (provision_count >= 0),
    embedded_count integer NOT NULL DEFAULT 0 CHECK (embedded_count >= 0),
    reused_embedding_count integer NOT NULL DEFAULT 0
        CHECK (reused_embedding_count >= 0),
    error_message text,
    started_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz
);

CREATE TABLE IF NOT EXISTS legal_documents (
    document_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_name text NOT NULL UNIQUE,
    source_url text NOT NULL DEFAULT '',
    content_hash char(64) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    first_collected_at timestamptz NOT NULL DEFAULT now(),
    last_collected_at timestamptz NOT NULL DEFAULT now(),
    last_collection_run_id uuid REFERENCES collection_runs(run_id)
);

CREATE TABLE IF NOT EXISTS legal_provisions (
    provision_id bigint PRIMARY KEY CHECK (provision_id > 0),
    document_id bigint NOT NULL
        REFERENCES legal_documents(document_id) ON DELETE RESTRICT,
    chapter_name text NOT NULL DEFAULT '',
    section_name text NOT NULL DEFAULT '',
    article_no text NOT NULL CHECK (length(btrim(article_no)) > 0),
    paragraph_no integer CHECK (paragraph_no IS NULL OR paragraph_no > 0),
    subparagraph_no integer
        CHECK (subparagraph_no IS NULL OR subparagraph_no > 0),
    title text NOT NULL DEFAULT '',
    content text NOT NULL CHECK (length(btrim(content)) > 0),
    search_text text NOT NULL CHECK (length(btrim(search_text)) > 0),
    search_compact text NOT NULL DEFAULT '',
    sort_order integer NOT NULL CHECK (sort_order >= 0),
    source_url text NOT NULL DEFAULT '',
    is_active boolean NOT NULL DEFAULT true,
    content_hash char(64) NOT NULL,
    embedding_input_hash char(64) NOT NULL,
    first_collected_at timestamptz NOT NULL DEFAULT now(),
    last_collected_at timestamptz NOT NULL DEFAULT now(),
    last_collection_run_id uuid REFERENCES collection_runs(run_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS legal_provisions_stable_key_idx
ON legal_provisions (
    document_id,
    article_no,
    COALESCE(paragraph_no, 0),
    COALESCE(subparagraph_no, 0)
);

CREATE INDEX IF NOT EXISTS legal_provisions_active_sort_idx
ON legal_provisions (is_active, sort_order, provision_id);

CREATE INDEX IF NOT EXISTS legal_provisions_document_idx
ON legal_provisions (document_id, is_active);

CREATE TABLE IF NOT EXISTS provision_embeddings (
    provision_id bigint NOT NULL
        REFERENCES legal_provisions(provision_id) ON DELETE CASCADE,
    embedding_model text NOT NULL,
    embedding_dimension integer NOT NULL CHECK (embedding_dimension = 768),
    embedding_input_hash char(64) NOT NULL,
    embedding vector(768) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (provision_id, embedding_model)
);

CREATE INDEX IF NOT EXISTS provision_embeddings_model_idx
ON provision_embeddings (embedding_model);

CREATE INDEX IF NOT EXISTS provision_embeddings_hnsw_cosine_idx
ON provision_embeddings
USING hnsw (embedding vector_cosine_ops);
